default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: ebay_crawler_development

test:
  <<: *default
  database: ebay_crawler_test
